version: '3.8'

services:
  web:
    image: srht_prod
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - storage:/storage
    ports:
      - 127.0.0.1:5000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
  storage:
