version: '3.8'

services:
  web:
    image: srht_dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - storage:/storage
      - "./:/app"
    ports:
      - 127.0.0.1:5000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
  storage:
