FROM python:3-alpine as base
# Dev image is much simpler
FROM base
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apk update && apk add postgresql-dev musl-dev gcc python3-dev sassc make curl
RUN apk add nginx libpq
COPY nginx/basic.conf /etc/nginx/http.d/default.conf
RUN apk update && apk add postgresql-dev musl-dev gcc python3-dev sassc make curl
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
CMD ["python", "/app/debug.py"]