version: '3.8'

services:
  web:
    image: srht_prod
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - storage:/storage
    ports:
      - 127.0.0.1:5000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_schema/srhtschema.sql:/docker-entrypoint-initdb.d/srhtschema.sql

volumes:
  postgres_data:
  storage:
