# fly.toml app configuration file generated for filehouse on 2023-10-05T07:53:03+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "filehouse"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  domain = "filehouse.fly.dev"
  errorfrom = "noreply@file.house"
  errorto = "admin@file.house"
  maxupload = "50 MB"
  owner = "oranges"
  owner_email = "admin@file.house"
  perpage = "40"
  protocol = "https"
  registration = "False"
  securecookie = "True"
  smtpfrom = "noreply@file.house"
  storage = "/storage/"
  support = "contact me on discord"

[processes]
  app = ""

[mounts]
  source = "filehouse_data"
  destination = "/storage"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
