[tool.poetry]
name = "filehouse"
version = "0.1.0"
description = "A simple file hosting service"
authors = ["oranges <email@oranges.net.nz>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.10"
bcrypt = "^4.0.1"
Flask = "^2.2.2"
Flask-Login = "^0.6.2"
Jinja2 = "^3.1.2"
psycopg2 = "^2.9.5"
six = "^1.16.0"
SQLAlchemy = "^2.0.2"
Werkzeug = "^2.2.2"
wheel = "^0.38.4"
docopt = "^0.6.2"
pystache = "^0.6.0"
python-dotenv = "^0.21.1"
gunicorn = "^20.1.0"
Flask-SQLAlchemy = "^3.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
