"""Initial database schema

Revision ID: 1371a0c98ad
Revises: None
Create Date: 2015-05-20 11:17:56.582791

"""

# revision identifiers, used by Alembic.
revision = '1371a0c98ad'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
