"""Add approval date

Revision ID: 168d21856e
Revises: 3a704a54392
Create Date: 2015-06-09 12:48:47.166658

"""

# revision identifiers, used by Alembic.
revision = '168d21856e'
down_revision = '3a704a54392'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('approvalDate', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'approvalDate')
    ### end Alembic commands ###
