"""Add upload table

Revision ID: 230feeb5b86
Revises: 168d21856e
Create Date: 2015-06-09 14:04:29.114345

"""

# revision identifiers, used by Alembic.
revision = '230feeb5b86'
down_revision = '168d21856e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
