"""Add tox IDs

Revision ID: 2a2cb310c7f
Revises: 5750db1d643
Create Date: 2015-07-17 17:47:41.265356

"""

# revision identifiers, used by Alembic.
revision = '2a2cb310c7f'
down_revision = '5750db1d643'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default='false')
    op.add_column('user', sa.Column('tox_id', sa.String(length=72), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tox_id')
    op.alter_column('upload', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default='false')
    ### end Alembic commands ###
