"""Add oauth tables

Revision ID: 2c27bce164d
Revises: 3dd77b90f3b
Create Date: 2015-11-22 15:09:57.256403

"""

# revision identifiers, used by Alembic.
revision = '2c27bce164d'
down_revision = '3dd77b90f3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
