"""Add rejected column

Revision ID: 3a704a54392
Revises: 1371a0c98ad
Create Date: 2015-06-09 12:30:56.039052

"""

# revision identifiers, used by Alembic.
revision = '3a704a54392'
down_revision = '1371a0c98ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rejected', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rejected')
    ### end Alembic commands ###
