"""Fix Tox IDs

Revision ID: 3dd77b90f3b
Revises: 2a2cb310c7f
Create Date: 2015-07-17 19:40:15.772002

"""

# revision identifiers, used by Alembic.
revision = '3dd77b90f3b'
down_revision = '2a2cb310c7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
