"""Add creation date and original name to uploads

Revision ID: 470b162dcd9
Revises: 2fdfac8b918
Create Date: 2015-06-14 12:25:57.467551

"""

# revision identifiers, used by Alembic.
revision = '470b162dcd9'
down_revision = '2fdfac8b918'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('upload', sa.Column('original_name', sa.Unicode(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'original_name')
    op.drop_column('upload', 'created')
    ### end Alembic commands ###
