"""Add non-nullable to uploads

Revision ID: 4c34ca870e0
Revises: 470b162dcd9
Create Date: 2015-06-14 15:05:37.769670

"""

# revision identifiers, used by Alembic.
revision = '4c34ca870e0'
down_revision = '470b162dcd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('upload', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('upload', 'shorthash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'shorthash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('upload', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('upload', 'hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
