"""added hide option to uploads table

Revision ID: 5750db1d643
Revises: 4c34ca870e0
Create Date: 2015-06-19 18:16:07.073631

"""

# revision identifiers, used by Alembic.
revision = '5750db1d643'
down_revision = '4c34ca870e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('hidden', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'hidden')
    ### end Alembic commands ###
